server:
  port: 8082

spring:
  application:
    name: business-service

data:
  service:
    url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000
        loggerLevel: basic

logging:
  level:
    com.example.businessservice.client: DEBUG
    feign: INFO
